# Site settings
title: A Note of Creativity
description: >
  Programming doesn't mean just things you learn. It's a science. It's a science
  where __creativity__ means a lot. So let us be creative!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://barbu110.github.io" # the base hostname & protocol for your site

author:
  fullname: Victor Barbu
  github: barbu110
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown